name: GH3-Permadeath

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  BGH3PC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Packages
        run: sudo apt install p7zip-full
      
      - name: Pull Honeycomb-CLI binary package
        run: |
          curl -LO https://github.com/AddyMills/Honeycomb-CLI/releases/download/20251010/Honeycomb-Linux-x64-2025-10-10_Release.7z
          7z x Honeycomb-Linux-x64-2025-10-10_Release.7z
      
      - name: move files in a separate command strip thingy majig
        run: |
          mkdir COMPILED_PC && mkdir COMPILED_PC/Permadeath
          cp -R GH3/bgh3-permadeath/DATA COMPILED_PC/DATA

      - name: Honeycomb compile
        run: |
          cd Honeycomb-Linux-x64
          chmod u+x ./Honeycomb
          ./Honeycomb pak compile '../GH3/dl2000000001' -g GH3 -c PC -o '../COMPILED_PC/DATA/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_pc' -g GH3 -c PC -o '../COMPILED_PC/DATA/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_text' -g GH3 -c PC -o '../COMPILED_PC/DATA/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_f' -g GH3 -c PC -o '../COMPILED_PC/DATA/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_g' -g GH3 -c PC -o '../COMPILED_PC/DATA/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_i' -g GH3 -c PC -o '../COMPILED_PC/DATA/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_s' -g GH3 -c PC -o '../COMPILED_PC/DATA/Permadeath'
          ./Honeycomb pak compile '../GH3/bgh3-permadeath/patch' -g GH3 -c PC -o '../COMPILED_PC/DATA'
          ./Honeycomb pak compile '../GH3/bgh3-permadeath/patch_text' -g GH3 -c PC -o '../COMPILED_PC/DATA'
          ./Honeycomb pak compile '../GH3/bgh3-permadeath/patch_text_f' -g GH3 -c PC -o '../COMPILED_PC/DATA'
          ./Honeycomb pak compile '../GH3/bgh3-permadeath/patch_text_g' -g GH3 -c PC -o '../COMPILED_PC/DATA'
          ./Honeycomb pak compile '../GH3/bgh3-permadeath/patch_text_i' -g GH3 -c PC -o '../COMPILED_PC/DATA'
          ./Honeycomb pak compile '../GH3/bgh3-permadeath/patch_text_s' -g GH3 -c PC -o '../COMPILED_PC/DATA'
      
      - name: Upload release attachment
        uses: actions/upload-artifact@v4
        with:
          name: GH3-PC-Permadeath
          path: ./COMPILED_PC
          retention-days: 30


  PS3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Packages
        run: |
          sudo apt install p7zip-full libfuse2
      
      - name: Pull Honeycomb-CLI && onyx-cli binary package
        run: |
          curl -LO https://github.com/AddyMills/Honeycomb-CLI/releases/download/20251010/Honeycomb-Linux-x64-2025-10-10_Release.7z
          curl -LO https://github.com/mtolly/onyx/releases/download/20251011/onyx-20251011-linux-x64.AppImage
          7z x Honeycomb-Linux-x64-2025-10-10_Release.7z

      - name: Honeycomb compile
        run: |
          cd Honeycomb-Linux-x64
          chmod u+x ./Honeycomb
          cp -R ../GH3/PKG ../PKG
          ./Honeycomb pak compile '../GH3/dl2000000001' -g GH3 -c PS3 && mv '../GH3/DL2000000001.PAK.PS3' '../PKG/USRDIR/GH3 PERMADEATH PATCH'
          ./Honeycomb pak compile '../GH3/dl2000000001_pc' -g GH3 -c PS3 && mv '../GH3/DL2000000001_PC.PAK.PS3' '../PKG/USRDIR/GH3 PERMADEATH PATCH'
          ./Honeycomb pak compile '../GH3/dl2000000001_text' -g GH3 -c PS3 && mv '../GH3/DL2000000001_TEXT.PAK.PS3' '../PKG/USRDIR/GH3 PERMADEATH PATCH'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_f' -g GH3 -c PS3 && mv '../GH3/DL2000000001_TEXT_F.PAK.PS3' '../PKG/USRDIR/GH3 PERMADEATH PATCH'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_g' -g GH3 -c PS3 && mv '../GH3/DL2000000001_TEXT_G.PAK.PS3' '../PKG/USRDIR/GH3 PERMADEATH PATCH'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_s' -g GH3 -c PS3 && mv '../GH3/DL2000000001_TEXT_S.PAK.PS3' '../PKG/USRDIR/GH3 PERMADEATH PATCH'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_i' -g GH3 -c PS3 && mv '../GH3/DL2000000001_TEXT_I.PAK.PS3' '../PKG/USRDIR/GH3 PERMADEATH PATCH'

      - name: onyx-cli compile
        run: |
          cd ~/work/NS-GH-Permadeath/NS-GH-Permadeath
          chmod u+x ./onyx-20251011-linux-x64.AppImage
          mkdir ./COMPILED_PS3
          ./onyx-20251011-linux-x64.AppImage pkg UP0010-BLUS30074_00-GH3PERMDETH ./PKG --to ./COMPILED_PS3/GH3-PS3-PERMADEATH-V1.pkg

      - name: Upload release attachment
        uses: actions/upload-artifact@v4
        with:
          name: GH3-PS3-Permadeath
          path: ./COMPILED_PS3
          retention-days: 30


  xthreesixty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Comment
        run: echo GH3-X360 will eventually go here when I can get it to build properly.