name: GH3-Permadeath

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  BGH3PC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Packages
        run: sudo apt install p7zip-full
      
      - name: Pull Honeycomb-CLI binary package
        run: |
          curl -LO https://github.com/AddyMills/Honeycomb-CLI/releases/download/20251010/Honeycomb-Linux-x64-2025-10-10_Release.7z
          7z x Honeycomb-Linux-x64-2025-10-10_Release.7z

      - name: Honeycomb compile
        run: |
          cd Honeycomb-Linux-x64
          chmod u+x ./Honeycomb
          ./Honeycomb pak compile '../GH3/dl2000000001' -g GH3 -c PC -o '../COMPILED_PC/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_pc' -g GH3 -c PC -o '../COMPILED_PC/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_text' -g GH3 -c PC -o '../COMPILED_PC/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_f' -g GH3 -c PC -o '../COMPILED_PC/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_g' -g GH3 -c PC -o '../COMPILED_PC/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_i' -g GH3 -c PC -o '../COMPILED_PC/Permadeath'
          ./Honeycomb pak compile '../GH3/dl2000000001_text_s' -g GH3 -c PC -o '../COMPILED_PC/Permadeath'
          ./Honeycomb pak compile '../GH3/z_pc_mod/gh3ml/mods/Permadeath/pak/permadeath' -g GH3 -c PC -o '../COMPILED'
          cd ..
      
      - name: Upload release attachment
        uses: actions/upload-artifact@v4
        with:
          name: GH3-PC-Permadeath
          path: ./COMPILED_PC
          retention-days: 30


  PS3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Comment
        run: echo GH3-PS3 will eventually go here when I can get it to build properly.
      - name: Packages
        run: |
          sudo dpkg --add-architecture i386
          sudo apt install p7zip-full wine
      
      - name: Pull Honeycomb-CLI && onyx-cli binary package
        run: |
          curl -LO https://github.com/AddyMills/Honeycomb-CLI/releases/download/20251010/Honeycomb-Linux-x64-2025-10-10_Release.7z
          curl -LO https://github.com/mtolly/onyx/releases/download/20251011/onyx-command-line-20251011-windows-x64.zip
          7z x Honeycomb-Linux-x64-2025-10-10_Release.7z
          7z x onyx-command-line-20251011-windows-x64.zip

      - name: Honeycomb compile
        run: |
          mkdir COMPILED_PS3
          cd Honeycomb-Linux-x64
          chmod u+x ./Honeycomb
          ./Honeycomb pak compile '../GH3/dl2000000001' -g GH3 -c PS3 && mv '../GH3/DL2000000001.PAK.PS3' '../GH3/PKG/USRDIR/GH3 PERMADEATH PATCH/DL2000000001.PAK.PS3'
          ./Honeycomb pak compile '../GH3/dl2000000001_pc' -g GH3 -c PS3 && mv '../GH3/DL2000000001_PC.PAK.PS3' '../GH3/PKG/USRDIR/GH3 PERMADEATH PATCH/DL2000000001_PC.PAK.PS3'

      - name: onyx-cli compile
        run: | 
          cd ~/work/NS-GH-Permadeath/NS-GH-Permadeath/scripts
          wine cmd /c gh3-ps3.bat

      - name: Upload release attachment
        uses: actions/upload-artifact@v4
        with:
          name: GH3-PS3-Permadeath
          path: ./COMPILED_PS3
          retention-days: 30


  xthreesixty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Comment
        run: echo GH3-X360 will eventually go here when I can get it to build properly.